# Generated by Django 2.2 on 2019-10-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='answer',
            field=models.TextField(max_length=128, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.TextField(max_length=256, verbose_name='Вопрос'),
        ),
    ]
